---

- name: Uninstall nginx 
  hosts: all
  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped

    - name: uninstall nginx
      apt:
        name: nginx
        state: absent
